name: Build .icns Icon for macOS

on:
  workflow_dispatch:

jobs:
  build-icon:
    runs-on: macos-latest

    steps:
      - name: Build environment info
        run: |
          echo "::group::macOS system:"
          sw_vers
          sw_vers > diag.txt
          echo "Xcode CLT:"
          pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
          pkgutil --pkg-info=com.apple.pkg.CLTools_Executables >> diag.txt
          echo "::endgroup::"
      
      - name: Build environment info (Upload)
        uses: actions/checkout@v4
        with:
          name: diagnostics
          path: diag.txt        

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify .iconset exists
        run: |
          if [ ! -d "res/icons/mac/mac-ico.iconset" ]; then
            echo "Error: .iconset folder not found!"
            exit 1
          fi

      - name: Convert .iconset to .icns
        run: |
          mkdir -p build
          iconutil -c icns res/icons/mac/mac-ico.iconset -o build/mac-ico.icns

      - name: Verify .icns file exists
        run: |
          if [ ! -f "build/mac-ico.icns" ]; then
            echo "Error: .icns file not created!"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-ico.icns
          path: build/mac-ico.icns
